### PR TITLE
Passphrase tester : validate all words + word suggestions

### PR DESCRIPTION
**Pull request by air1one**
As discussed in #152 this is a suggestion to validate all the words in the passphrase tester.

Please check this out @luciorubeens @alexbarnsley and tell me if this looks good to you !

### CODE REVIEW

**Comment by air1one** [comment]
OK @luciorubeens I did hesitate between Electrum's way of doing this and Mycelium's, finally I implemented the Mycelium's way which I personally preferred (see my comment in #152 ). But I'm ok doing as you suggest too 👍 
Will adapt it when I have some time next week.

**Comment by alexbarnsley** [comment]
@air1one did you get round to making these changes? 😁

**Comment by air1one** [comment]
Uohh you're right @alexbarnsley I left this one behind 😮  Will definitely finish it, right now I need to focus on what Brian asked me (end-to-end testing for core), so next week will get back to it (for real this time 😅 will put a reminder). Sorry about that.

**Comment by air1one** [comment]
OK you can check my last commit @alexbarnsley 👍 

Created a new component for passphrase input, right now just used here in the passphrase tester but then we could adapt it a bit to use it in the wallet import page.

**Pull request merged**
