### PR TITLE
indonesia translation

### PR DESCRIPTION
**Pull request by lutfinn**
## Proposed changes
i want to contribute for ark wallet mobile translation into bahasa indonesia .. indonesian language.
thanks for jarunix and syarrf who introduce me about this project
## Types of changes
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (improve a current implementation without adding a new feature or fixing a bug)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Build (changes that affect the build system)
- [ ] Docs (documentation only changes)
- [ ] Test (adding missing tests or fixing existing tests)
- [x] Other... Please describe:
i only 
- add 1 file id.json in asset/i18n for indonesia translation
- edit setting-data.ts and add line for indonesia language

## Checklist
- [x] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

image

### CODE REVIEW

**Comment by amuchtar** [comment]
maaf bro komandan tidak memberi perintah

**Comment by arkindonesia** [comment]
Passphrase ... Tetap tidak usah di ganti ... Tidak usah diganti Mazbro

**Comment by happyphoenix** [comment]
yoi !

**Comment by happyphoenix** [comment]
kelihatannya udah cukup bagus dah !

**Comment by luciorubeens** [comment]
@lutfinn Thank you! 👍

**Comment by boldninja** [comment]
@lutfinn Can you provide me with your ARK address for GitHub bounty? You can also contact me on ARK's Slack - https://ark.io/slack (username : boldninja) and direct message me your address there.

**Pull request merged**
