### PR TITLE
chore: update dependencies and platforms libraries

### PR DESCRIPTION
**Pull request by luciorubeens**
Hey @alexbarnsley, I spent a few days trying to make it work and I think I'm finally done. It has been tested on Xcode, iPhone Device and Android Studio. Can you check on an Android device?

I also removed the small modals, it was an old request from Oleg and also wipes out keyboard problems.

### CODE REVIEW

**Comment by dated** [comment]
Looks like all angular packages have to be updated to 5.x.x

```
ERROR [karma]: Error: Error: Metadata version mismatch for module /home/circleci/mobile-wallet/node_modules/@ionic/storage/ionic-storage.d.ts, found version 4, expected 3, resolving symbol AppModule in /home/circleci/mobile-wallet/src/app/app.module.ts, resolving symbol AppModule in /home/circleci/mobile-wallet/src/app/app.module.ts, resolving symbol AppModule in /home/circleci/mobile-wallet/src/app/app.module.ts
```

**Comment by luciorubeens** [comment]
Oops, this was working locally before rebase. Will take a look tomorrow.

**Comment by luciorubeens** [comment]
@alexbarnsley Here we go. I recommend doing a fresh installation:

```shell
npm install -g cordova@8.1.2 ionic@4.2.1
rm -rf node_modules plugins platforms
npm i
```

**Comment by luciorubeens** [comment]
Looks like CircleCI is broken 😢

**Comment by dated** [comment]
Strange that it's not finding `ng` anymore. Might have to add angular/cli to the global `Pre dependencies` in the circleci config.

**Comment by dated** [comment]
Actually the ionic and cordova versions need to be changed as well. You can try by changing https://github.com/ArkEcosystem/mobile-wallet/blob/master/.circleci/config.yml#L15 to:

```
command: sudo npm i -g ionic@4.2.1 cordova@8.1.2 @angular/cli
```

**Comment by dated** [comment]
```
found 122 vulnerabilities (30 low, 74 moderate, 18 high)
```

**Comment by luciorubeens** [comment]
👍🏻

**Pull request merged**
