### PR TITLE
Fix critical vulnerabilities

### PR DESCRIPTION
**Pull request by h1psterx**
Result of the `npm audit` before:

`found 303 vulnerabilities (99 low, 154 moderate, 45 high, 5 critical) in 16867 scanned packages`

After:

`found 113 vulnerabilities (32 low, 65 moderate, 16 high) in 11564 scanned packages`

For others it is necessary to update the main dependencies, like `cordova-ios` and `cordova-android`, I preferred not to touch.

### CODE REVIEW

**Comment by luciorubeens** [comment]
Thanks, I'm working on updating the dependencies in the [`fix/update-deps`](https://github.com/ArkEcosystem/mobile-wallet/tree/fix/update-deps).

**Comment by luciorubeens** [comment]
Ops, sorry. You fixed some that I did not. Good catch!

**Comment by boldninja** [comment]
@h1psterx Can you provide me with your ARK address for GitHub bounty? You can also contact me on ARK's Slack - https://ark.io/slack (username : boldninja) and direct message me your address there.

**Comment by h1psterx** [comment]
@boldninja AJeytWmtqWDLkrj6zkxSqfsRfk7BFTDF74 thank you

**Pull request merged**
