### PR TITLE
Add Polish translation strings

### PR DESCRIPTION
**Pull request by FloryanFilip**
## Proposed changes
Untill now, the ARK mobile-wallet had no Polish translations available.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (improve a current implementation without adding a new feature or fixing a bug)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Build (changes that affect the build system)
- [ ] Docs (documentation only changes)
- [ ] Test (adding missing tests or fixing existing tests)
- [x] Other... Please describe:
- Added pl.json in asset/i18n for polish translations
- Added one line of code in setting-data.ts to reflect the newly added translation

## Checklist

-  [x] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments
# Resolves:#301
Screenshot_1554289760

### CODE REVIEW

**Comment by FloryanFilip** [comment]
Unsure whether I should rename my commit to follow contribution guidelines or should I leave it as is?

**Comment by luciorubeens** [comment]
Hey @FloryanFilip, don't worry. I changed the commit title. Thank you 👍

**Comment by boldninja** [comment]
@FloryanFilip Can you provide me with your ARK address for GitHub bounty? You can also contact me on ARK's Slack - https://ark.io/slack (username : boldninja) and direct message me your address there.

**Comment by FloryanFilip** [comment]
k28+!L

**Pull request merged**
